spring:
    application:
        name: authuser-service
    config:
        import: 'configserver:'
    cloud:
        config:
            discovery:
                serviceId: config-server
            username: configserver
            password: '123cs'