server:
  port: 8087
  servlet:
    context-path: '/authuser/'

auth:
  jwtSecret: t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWn
  jwtExpirationMs: 14400000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: authuser-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
